---
title: ''
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval = TRUE)
```

## Univariate Hawkes 

```{r}
params <- list(mu = 0.5, alpha = 1, beta = 1.5)
simulated_times <- stelfi::sim_hawkes(mu = params[["mu"]], alpha = params[["alpha"]], 
                                      beta = params[["beta"]], n = 40, seed = 654)
```

### Negative log-liklihood calculations

```{r}
## benchmark
require(hawkes)
likelihoodHawkes(lambda0 = params[["mu"]], alpha = params[["alpha"]], 
                 beta = params[["beta"]], history = simulated_times)
```

```{r}
require(RTMB)
## check against repo RTMB template
source("rtmb.r") 
times <- list(times = simulated_times)
abratio <- params[["alpha"]]/params[["beta"]]
pars <- list(log_mu = log(params[["mu"]]), logit_abratio = log(abratio/(1 - abratio)), 
             log_beta = log(params[["beta"]]))
hawkes_rtmb(params = pars)
```


```{r}
## check against repo analytical fun
source("analytical.r")
pars <- list(mu = params[["mu"]], abratio = params[["alpha"]]/params[["beta"]], 
             beta = params[["beta"]])
hawkes_analytic(params = pars, times = simulated_times)

```

### Parameter recovery

```{r}
## benchmark
require(emhawkes)
h <- new("hspec", mu = params[["mu"]], alpha = params[["alpha"]], beta = params[["beta"]])
## emhawkes requires the inter arrival times to fit the model
inter <- diff(simulated_times)
fit_em <- hfit(object = h, inter_arrival = inter)
summary(fit_em)$estimate
```
```{r}
## check against repo RTMB template
## function from rtmb.r
abratio <- params[["alpha"]]/params[["beta"]]
pars <- list(log_mu = log(params[["mu"]]), logit_abratio = log(abratio/(1 - abratio)), 
             log_beta = log(params[["beta"]]))
obj <- MakeADFun(hawkes_rtmb, pars, silent = TRUE)
opt <- nlminb(obj$par, obj$fn, obj$gr)
summary(sdreport(obj), "report")
```

```{r}
## check against repo analytical fun
## function from analytical.r
pars <- c(mu = params[["mu"]], abratio = params[["alpha"]]/params[["beta"]], 
             beta = params[["beta"]])
## using optim just for now
fit <- optim(par = pars, fn = hawkes_analytic, times = simulated_times, 
             method = "Nelder-Mead", hessian = TRUE)
## parameter ests
fit$par
## alpha
as.numeric(fit$par[2]*fit$par[3])
## standard errors
fit$hessian |> solve() |> diag() |> sqrt()
```